services:
  ravuno:
    container_name: ravuno
    build:
      dockerfile: Dockerfile
    ports:
      - "1868:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DataStorage=Data Source=/app/data/ravuno.db
      - FetchAndSendSettings__Interval=1.00:00:00
      - UpdateConfigurationsPath=/app/config/updates
      - EmailSettings__SmtpHost=your.smtp.server
      - EmailSettings__SmtpPort=587
      - EmailSettings__SmtpUsername=your-username
      - EmailSettings__SmtpPassword=your-password
      - EmailSettings__FromEmail=noreply@example.com
      - EmailSettings__FromName=Ravuno
      - EmailSettings__EnableSsl=true
    restart: unless-stopped
    volumes:
      - ./docker/data:/app/data
      - ./docker/config:/app/config
